package com.edu.runtime.test;
/*
 * Catch는 여러번 가능하다.
 * 
 */
public class RuntimeExceptionTest2 {

	public static void main(String[] args) {
		String[] str = {
				"Hello",
				"No, I mean it",
				"Nice to meet you"
		};
		
		int i=0; 
		while(i<=3) {
			try {
				System.out.println(str[i]);		// Exception은 줄단위로 실행되다가 발생함
			} catch(NullPointerException e) {
				System.out.println("Nice Catch1~~");
			} catch(ArrayIndexOutOfBoundsException e) {
				System.out.println("Nice Catch2~~");
			} catch(ArithmeticException e) {	// 분모를 0으로 하면 발생
				System.out.println("Nice Catch3~~");
			}
			
			i++;
		}//
		System.out.println("while loop end...");
	}//main

}//class
